
version: 2
sources:
  - name: transaction
    tables:
      - name: transactions
  - name: order
    tables:
      - name: order_clean
  - name: traffic
    tables:
<<<<<<< HEAD
      - name: traffic
=======
      - name: traffic

models:
  - name: transactions_clean
  - name: email
>>>>>>> a632f32aabd7dff81f712c611e3f50acc898baa2
