
version: 2
sources:
  - name: transaction
    tables:
      - name: transactions
  - name: order
    tables:
      - name: order_clean
  - name: traffic
    tables:
      - name: traffic

models:
  - name: transactions_clean
  - name: email
  - name: email_aggr
  - name: transac_aggr
  - name: traffic
  - name: traffic_campagne
